import streamlit as st
from database import crud
from fpdf import FPDF
import io

def create_pdf_report(doc_name, clauses, contradictions, audit_result) -> bytes:
    """Generates a professional PDF audit report using fpdf2."""
    pdf = FPDF()
    pdf.add_page()
    
    # Title
    pdf.set_font("helvetica", "B", 24)
    pdf.set_text_color(99, 110, 250) # Blue
    pdf.cell(0, 15, "LQ-LegalAI Contract Audit Report", ln=True, align="C")
    
    # Subtitle
    pdf.set_font("helvetica", "I", 12)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 10, f"Target Document: {doc_name}", ln=True, align="C")
    pdf.cell(0, 10, "Generated by LQ-LegalAI Orchestration Platform", ln=True, align="C")
    pdf.ln(10)
    
    # AI Audit Scores (Agent 16)
    pdf.set_font("helvetica", "B", 16)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 10, "1. Agent 16 AI Audit Verification", ln=True)
    
    pdf.set_font("helvetica", "", 12)
    pdf.cell(0, 8, f"Overall Audit Score: {audit_result.audit_score}/100", ln=True)
    pdf.cell(0, 8, f"AI Trust Score: {audit_result.trust_score}/100", ln=True)
    pdf.cell(0, 8, f"Confidence Score: {audit_result.confidence_score}/100", ln=True)
    pdf.ln(5)
    
    pdf.set_font("helvetica", "B", 12)
    pdf.cell(0, 8, "Audit Summary:", ln=True)
    pdf.set_font("helvetica", "", 11)
    pdf.multi_cell(0, 6, audit_result.audit_summary)
    pdf.ln(5)
    
    pdf.set_font("helvetica", "B", 12)
    pdf.cell(0, 8, "Hallucination & Citation Check:", ln=True)
    pdf.set_font("helvetica", "", 11)
    pdf.multi_cell(0, 6, f"Hallucination Risks: {audit_result.hallucination_risks}")
    pdf.multi_cell(0, 6, f"Citation Accuracy: {audit_result.citation_accuracy}")
    pdf.ln(10)
    
    # Executive Summary
    pdf.set_font("helvetica", "B", 16)
    pdf.cell(0, 10, "2. Executive Risk Summary", ln=True)
    
    high_risks = len([c for c in clauses if c['risk_level'] == 'High'])
    med_risks = len([c for c in clauses if c['risk_level'] == 'Medium'])
    
    pdf.set_font("helvetica", "", 12)
    pdf.cell(0, 8, f"Total Clauses Parsed: {len(clauses)}", ln=True)
    pdf.cell(0, 8, f"High Risk Clauses: {high_risks}", ln=True)
    pdf.cell(0, 8, f"Medium Risk Clauses: {med_risks}", ln=True)
    pdf.cell(0, 8, f"Inconsistencies/Contradictions: {len(contradictions)}", ln=True)
    pdf.ln(10)
    
    # Return as bytes
    return pdf.output()

st.title("📋 Audit Report Generator (Agent 16)")
st.markdown("Agent 16 evaluates the entire document analysis for hallucinations and generates a comprehensive PDF Audit Report.")

doc_id = st.session_state.active_doc_id
doc_name = st.session_state.active_doc_name

if not doc_id:
    st.warning("⚠️ Please select an active document in the sidebar to generate an audit report.")
else:
    st.info(f"Preparing Audit Report for: **{doc_name}**")
    
    if st.button("Run Master Audit & Generate PDF"):
        with st.spinner("Agent 16 is auditing all analyses and compiling the PDF..."):
            try:
                clauses = crud.get_clauses_for_document(doc_id)
                contradictions = crud.get_contradictions_for_document(doc_id)
                
                from agents.audit_agent import perform_macro_audit
                audit_result = perform_macro_audit(doc_name, clauses, contradictions)
                
                # Layout scores
                st.markdown("### 🛡️ Agent 16 Verification Scores")
                c1, c2, c3 = st.columns(3)
                c1.metric("Audit Score", f"{audit_result.audit_score}/100")
                c2.metric("Trust Score", f"{audit_result.trust_score}/100")
                c3.metric("Confidence Score", f"{audit_result.confidence_score}/100")
                
                st.markdown(f"**📝 Summary:** {audit_result.audit_summary}")
                st.markdown(f"**🤖 Hallucination Check:** {audit_result.hallucination_risks}")
                st.markdown(f"**📚 Citation Check:** {audit_result.citation_accuracy}")
                
                # Generate PDF
                pdf_bytes = create_pdf_report(doc_name, clauses, contradictions, audit_result)
                
                st.download_button(
                    label="📥 Download PDF Audit Report",
                    data=bytes(pdf_bytes),
                    file_name=f"Audit_Report_{doc_name.replace(' ', '_')}.pdf",
                    mime="application/pdf"
                )
                
                st.success("PDF Report generated successfully!")
                crud.add_audit_log("audit_report", f"Agent 16 generated PDF audit for '{doc_name}'")
            except Exception as e:
                st.error(f"Failed to generate audit report: {e}")
